spring.application.name=jira
spring.data.mongodb.uri=mongodb+srv://vedha:1894@cluster0.p0tmvhx.mongodb.net/elevenceProject?retryWrites=true&w=majority
spring.data.mongodb.database=elevenceProject
spring.mongodb.uri=mongodb+srv://vedha:1894@cluster0.p0tmvhx.mongodb.net/elevenceProject?retryWrites=true&w=majority
spring.mongodb.database=elevenceProject

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=crisvedharaj@gmail.com
spring.mail.password=gxcu bqhc kbaa zuwa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000



